services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      - DATABASE_NAME=${{ shared.DATABASE_NAME }}
      - ELASTICSEARCH_PASSWORD=${{ shared.ELASTICSEARCH_PASSWORD }}
      - ELASTICSEARCH_URL=${{ shared.ELASTICSEARCH_URL }}
      - ELASTICSEARCH_USERNAME=${{ shared.ELASTICSEARCH_USERNAME }}
      - KAFKA_BOOTSTRAP_SERVERS=${{ shared.KAFKA_BOOTSTRAP_SERVERS }}
      - MONGO_URI=${{ shared.MONGO_URI }}
    restart: always